[[constraint]]
name = "cloud.google.com/go"
version = "0.93.3"

[[constraint]]
name = "github.com/spf13/cobra"
version = "1.2.1"

[[constraint]]
name = "github.com/sarulabs/di"
version = "2.4.2"

[[constraint]]
name = "github.com/stevenroose/gonfig"
version = "0.1.5"