[[constraint]]
name = "github.com/spf13/cobra"
version = "1.2.1"

[[constraint]]
name = "github.com/sarulabs/di"
version = "2.4.2"

[[constraint]]
name = "github.com/stevenroose/gonfig"
version = "0.1.5"

[[constraint]]
name = "github.com/otiai10/gosseract"
version = "2.3.1"

[[constraint]]
name = "go.uber.org/zap"
version = "1.19.0"

[[constraint]]
name = "github.com/pkg/errors"
version = "0.9.1"